import { useEffect } from 'react'
import { Link } from 'react-router-dom'
import Header from '../components/Header'

function Section({ title, children }) {
  return (
    <div className="mb-8">
      <h2 className="font-serif text-xl font-bold mb-3" style={{ color: '#E2B96F' }}>{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed" style={{ color: 'rgba(255,255,255,0.60)' }}>
        {children}
      </div>
    </div>
  )
}

export default function TermsOfService() {
  useEffect(() => { window.scrollTo(0, 0) }, [])

  return (
    <div className="min-h-screen">
      <Header />
      <main className="max-w-3xl mx-auto px-4 py-16">

        {/* Header */}
        <div className="mb-12">
          <p className="text-xs font-semibold uppercase tracking-widest mb-3" style={{ color: 'rgba(201,168,76,0.60)' }}>Legal</p>
          <h1 className="font-serif text-4xl font-bold text-white mb-4">Terms of Service</h1>
          <p className="text-sm" style={{ color: 'rgba(255,255,255,0.35)' }}>Last updated: March 2026</p>
        </div>

        <div
          className="rounded-2xl p-8"
          style={{ background: '#1E2435', border: '1px solid rgba(255,255,255,0.07)' }}
        >
          <Section title="1. Acceptance of Terms">
            <p>By accessing or using CryptoGive ("the Platform", "we", "us"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Platform.</p>
            <p>We reserve the right to update these terms at any time. Continued use of the Platform after changes constitutes acceptance of the revised terms.</p>
          </Section>

          <Section title="2. Description of Service">
            <p>CryptoGive is a <strong style={{ color: 'rgba(255,255,255,0.80)' }}>non-custodial donation interface</strong>. We provide a frontend that allows users to send cryptocurrency directly from their own wallets to verified charitable organizations.</p>
            <p>We do <strong style={{ color: 'rgba(255,255,255,0.80)' }}>not</strong>:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Hold, custody, or control any user funds at any time</li>
              <li>Process fiat currency</li>
              <li>Act as a money services business, exchange, or financial intermediary</li>
              <li>Guarantee the outcome of any blockchain transaction</li>
            </ul>
            <p>All transactions are executed directly on-chain between the donor's wallet and the recipient organization's wallet.</p>
          </Section>

          <Section title="3. Eligibility">
            <p>You must be at least 18 years of age to use this Platform. By using the Platform, you represent and warrant that you meet this requirement and that you have the legal capacity to enter into these Terms.</p>
          </Section>

          <Section title="4. User Responsibilities">
            <p>You are solely responsible for:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>The security and backup of your own wallet and private keys</li>
              <li>Ensuring you send the correct amount to the correct address</li>
              <li>Understanding that blockchain transactions are irreversible</li>
              <li>Compliance with all applicable laws in your jurisdiction, including tax laws</li>
              <li>The accuracy of profile information you provide (name, email, tax number)</li>
            </ul>
          </Section>

          <Section title="5. Prohibited Uses">
            <p>You agree not to use the Platform to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Violate any applicable law or regulation</li>
              <li>Engage in money laundering, fraud, or any other illegal activity</li>
              <li>Transmit funds derived from criminal activity</li>
              <li>Attempt to circumvent any security measures</li>
              <li>Impersonate any person or organization</li>
            </ul>
          </Section>

          <Section title="6. No Financial or Tax Advice">
            <p>Nothing on this Platform constitutes financial, investment, legal, or tax advice. Tax documentation generated by the Platform is provided for <strong style={{ color: 'rgba(255,255,255,0.80)' }}>informational purposes only</strong>.</p>
            <p>The deductibility of charitable donations depends on your individual circumstances and jurisdiction. You should consult a qualified tax professional before claiming any deduction.</p>
          </Section>

          <Section title="7. Third-Party Services">
            <p>The Platform integrates with third-party services including WalletConnect, blockchain networks, and price data providers. We are not responsible for the availability, accuracy, or conduct of these third-party services.</p>
            <p>Your use of connected wallets is governed by the terms of your wallet provider.</p>
          </Section>

          <Section title="8. Disclaimer of Warranties">
            <p>The Platform is provided "as is" and "as available" without warranties of any kind, express or implied. We do not warrant that the Platform will be uninterrupted, error-free, or free of viruses or other harmful components.</p>
          </Section>

          <Section title="9. Limitation of Liability">
            <p>To the maximum extent permitted by law, CryptoGive and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to lost funds, loss of data, or loss of profits, arising out of or relating to your use of the Platform.</p>
            <p>In no event shall our total liability exceed the amount of fees (if any) paid by you to us in the twelve months preceding the claim.</p>
          </Section>

          <Section title="10. Governing Law">
            <p>These Terms shall be governed by and construed in accordance with applicable law. Any disputes shall be resolved through binding arbitration, waiving the right to a jury trial or class action.</p>
          </Section>

          <Section title="11. Contact">
            <p>If you have questions about these Terms, please contact us through the Platform.</p>
          </Section>
        </div>

        <div className="flex gap-4 mt-8">
          <Link to="/privacy" className="btn-secondary text-sm">Privacy Policy →</Link>
          <Link to="/refund-policy" className="btn-secondary text-sm">Refund Policy →</Link>
          <Link to="/" className="text-sm flex items-center" style={{ color: 'rgba(255,255,255,0.35)' }}>← Back to Home</Link>
        </div>
      </main>
    </div>
  )
}
